### PR TITLE
Setup documentation

### PR DESCRIPTION
**Pull request by CreaturePhil**
At least two people need to approved this pull request before merge!

To see the docs: https://github.com/FakeSloth/buma/blob/setup/docs/setup.md

Find any spelling or grammar mistakes? Also, any part you don't understand?

Try running this locally on your computer. You'll have to clone the setup branch.

### CODE REVIEW

**Comment by CreaturePhil** [comment]
@Kouhai-Senpai @gigavinyl @sevagsatamian @stevoduhhero

**Comment by CreaturePhil** [comment]
Wow, no one really?! Is it that much to take in? :scream:

**Comment by margaretjoanmiller** [comment]
@CreaturePhil Sorry, I can't get MongoDB working properly :confused:. The documentation looks good though, should I just merge it anyway?

**Comment by CreaturePhil** [comment]
@gigavinyl One more person should double checked on it. @Kouhai-Senpai @sevagsatamian 

Also, why isn't MongoDB working properly on your computer?

**Comment by margaretjoanmiller** [comment]
@CreaturePhil I don't know. I installed mogo with `npm install -g mongoose` and when I try to run `mongod` it says command not found :confused:.  I know npm is working because I installed bower with it and it works fine.

**Comment by CreaturePhil** [comment]
Mongoose isn't MongoDB. Mongoose is a tool to be used with MongoDB.

> MongoDB object modeling tool designed to work in an asynchronous environment.

To install MongoDB, see these [instructions](http://docs.mongodb.org/manual/administration/install-on-linux/).

**Comment by margaretjoanmiller** [comment]
@CreaturePhil Oh, ok. Thanks! I'm not sure why I thought mongoose installed MongoDB :no_mouth:.

**Comment by CreaturePhil** [comment]
@gigavinyl I updated the docs to be more clear. :smile:

**Comment by CreaturePhil** [comment]
@gigavinyl Should I even link to the article or is it better if I explained it within the docs?

**Comment by margaretjoanmiller** [comment]
@CreaturePhil I got it working :smile:. It's just supposed to say "Hello World!" right? Also, for some reason, when I installed the dependencies with `node install -g`, it still made me install them in the buma directory. I know I could just make symbolic links but is there a better way of doing this? I think linking to the articles on the Mongo website is fine :smile:.

**Comment by CreaturePhil** [comment]
@gigavinyl Yeah, it was supposed to say "Hello World"! Wait, `node install -g`?! Do you mean `npm install -g`? You usually want to install dependencies separately for each project. Also, I meant linking to the scotch article not the MongoDB website.

**Comment by margaretjoanmiller** [comment]
@CreaturePhil Sorry, I meant npm. Oh, sorry; yeah, that scotch article looks good :smile:. I think transferring it into the docs might be a little overwhelming.

**Comment by CreaturePhil** [comment]
@gigavinyl No I meant simplifying it in the docs.

**Comment by margaretjoanmiller** [comment]
@CreaturePhil Oh, well that actually might be better then.

**Comment by CreaturePhil** [comment]
Also, don't delete this branch.

**Comment by CreaturePhil** [comment]
@gigavinyl Is this good?

> We are using the MongoDB NoSql database. MongoDB makes working with a database 
> simple and elegant, providing agility and freedom to scale. The benefits of 
> using a document database like MongoDB means that you can work with JSON-style 
> documents in the frontend (client) and the backend (server).
> 
> To install MongoDB on your computer, see these [instructions][installation].
> 
> Before we can start creating and saving documents in our database, we have to 
> start up MongoDB. There won’t be anything to save to if the service isn’t 
> started! The command is very simple to get MongoDB up and running:
> 
> ``` bash
> $ mongod
> ```
> 
> Once we have issue this command, MongoDB will start up and you should see: 
> `waiting for connections on port 27017`.
> 
> In our node.js application, we are using `mongoose` to connect to a MongoDB 
> database and it allows us to have access to the MongoDB commands.
> 
> [installation]: http://docs.mongodb.org/manual/installation

**Comment by margaretjoanmiller** [comment]
@CreaturePhil Looks good :smile:.

**Comment by CreaturePhil** [comment]
:shipit: Okay, I'm just going to merge. Onto the next part!!!!

**Comment by CreaturePhil** [comment]
PS: Don't delete this branch. :+1:

**Pull request merged**
